"""Created change password class

Revision ID: 1333b5bd61d5
Revises: 1b8ef5fac825
Create Date: 2025-03-04 02:48:03.513975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1333b5bd61d5'
down_revision: Union[str, None] = '1b8ef5fac825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
