"""Add profile tutorial status

Revision ID: 19f858e95032
Revises: 29cafea606b9
Create Date: 2025-04-02 22:12:07.820131

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f858e95032'
down_revision: Union[str, None] = '29cafea606b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_tutorial_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_tutorial_completed')
    # ### end Alembic commands ###
