"""Add recovery info to database

Revision ID: 1b8ef5fac825
Revises: 48294ef6abb9
Create Date: 2025-03-03 19:27:39.494788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8ef5fac825'
down_revision: Union[str, None] = '48294ef6abb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recovery_email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('recovery_phone_number', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'recovery_phone_number')
    op.drop_column('user', 'recovery_email')
    # ### end Alembic commands ###
