"""Add FAQ database

Revision ID: 23c4696d9900
Revises: 510c0f972c43
Create Date: 2025-03-16 16:38:32.737526

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c4696d9900'
down_revision: Union[str, None] = '510c0f972c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq')
    # ### end Alembic commands ###
