"""Create reviews table

Revision ID: 5424d86d90fd
Revises: 20924e72b3a1
Create Date: 2025-04-10 17:17:52.410668

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5424d86d90fd'
down_revision: Union[str, None] = '20924e72b3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
