"""Added renter preference data table

Revision ID: a7a3fe651ded
Revises: b036a9888d6f
Create Date: 2025-02-27 01:01:02.298956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'a7a3fe651ded'
down_revision: Union[str, None] = 'b036a9888d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renterpreference',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('num_bedrooms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('num_bathrooms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('realty_company', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('included_utilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('security_deposit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lease_start_date', sa.Date(), nullable=True),
    sa.Column('lease_end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renterpreference')
    # ### end Alembic commands ###
