"""Add column phone_number, bio, and profile_type to updating user

Revision ID: b036a9888d6f
Revises: b53a636a61dd
Create Date: 2025-02-26 03:11:13.716471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b036a9888d6f'
down_revision: Union[str, None] = 'b53a636a61dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
