"""Add profile visibility to database

Revision ID: b2366c127cab
Revises: ca051da4e862
Create Date: 2025-03-02 20:11:44.902019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2366c127cab'
down_revision: Union[str, None] = 'ca051da4e862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_visibility', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_visibility')
    # ### end Alembic commands ###
