"""Add column bio and profile_type to User model

Revision ID: b53a636a61dd
Revises: 1a31ce608336
Create Date: 2025-02-25 22:46:56.428709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b53a636a61dd'
down_revision: Union[str, None] = '1a31ce608336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    op.add_column('user', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_type', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_column('user', 'profile_type')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
