"""Add columns hasTakenQuiz and quizResponses to uesr model

Revision ID: b95a8d6f6a24
Revises: 510c0f972c43
Create Date: 2025-03-16 03:06:34.746088

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95a8d6f6a24'
down_revision: Union[str, None] = '510c0f972c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hasTakenRoommateQuiz', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('cleanScore', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('visitScore', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sleepTime', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('pets', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('smoking', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('alcoholScore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'alcoholScore')
    op.drop_column('user', 'smoking')
    op.drop_column('user', 'pets')
    op.drop_column('user', 'sleepTime')
    op.drop_column('user', 'visitScore')
    op.drop_column('user', 'cleanScore')
    op.drop_column('user', 'hasTakenRoommateQuiz')
    # ### end Alembic commands ###
