"""add column active_profile to user model

Revision ID: e658deb4815b
Revises: 1b8ef5fac825
Create Date: 2025-03-04 02:59:06.950423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e658deb4815b'
down_revision: Union[str, None] = '1b8ef5fac825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
