"""added active_profile_type column in user model

Revision ID: fa9d9b63e57c
Revises: 1333b5bd61d5
Create Date: 2025-03-06 15:26:05.294623

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9d9b63e57c'
down_revision: Union[str, None] = '1333b5bd61d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_profile_type', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_profile_type')
    # ### end Alembic commands ###