/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SettingsImport } from './routes/settings'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutRoommatesImport } from './routes/_layout/roommates'
import { Route as LayoutRoommateagreementImport } from './routes/_layout/roommate_agreement'
import { Route as LayoutRoommateQuizImport } from './routes/_layout/roommate-quiz'
import { Route as LayoutRenterlistingsImport } from './routes/_layout/renter_listings'
import { Route as LayoutMessagingImport } from './routes/_layout/messaging'
import { Route as LayoutListingsImport } from './routes/_layout/listings'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutChatImport } from './routes/_layout/chat'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRoommatesRoute = LayoutRoommatesImport.update({
  path: '/roommates',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRoommateagreementRoute = LayoutRoommateagreementImport.update({
  path: '/roommate_agreement',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRoommateQuizRoute = LayoutRoommateQuizImport.update({
  path: '/roommate-quiz',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRenterlistingsRoute = LayoutRenterlistingsImport.update({
  path: '/renter_listings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMessagingRoute = LayoutMessagingImport.update({
  path: '/messaging',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutListingsRoute = LayoutListingsImport.update({
  path: '/listings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChatRoute = LayoutChatImport.update({
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/chat': {
      preLoaderRoute: typeof LayoutChatImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/listings': {
      preLoaderRoute: typeof LayoutListingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/messaging': {
      preLoaderRoute: typeof LayoutMessagingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/renter_listings': {
      preLoaderRoute: typeof LayoutRenterlistingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/roommate-quiz': {
      preLoaderRoute: typeof LayoutRoommateQuizImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/roommate_agreement': {
      preLoaderRoute: typeof LayoutRoommateagreementImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/roommates': {
      preLoaderRoute: typeof LayoutRoommatesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutChatRoute,
    LayoutItemsRoute,
    LayoutListingsRoute,
    LayoutMessagingRoute,
    LayoutRenterlistingsRoute,
    LayoutRoommateQuizRoute,
    LayoutRoommateagreementRoute,
    LayoutRoommatesRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SettingsRoute,
  SignupRoute,
])

/* prettier-ignore-end */
